version: '3.8'

services:
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.0
    hostname: etcd-00
    ports:
      - 2379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - etcd_data:/data.etcd
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: unless-stopped
volumes:
  etcd_data:
